# --- Project Configuration ---
project:
  type: default
  output-dir: output

# --- Execution Settings ---
execute:
  freeze: auto

# --- Bibliography & Citations
bibliography: references.bib
csl: elsevier-vancouver.csl

# --- PDF Format Configuration ---
format:
  pdf:
    # --- Document Settings ---
    documentclass: scrartcl
    papersize: letter
    fontsize: 12pt
    toc: false
    number-sections: false
    
    # --- Engine and Fonts Settings---
    pdf-engine: xelatex
    mainfont: "Source Serif Pro"
    sansfont: "Source Sans Pro"
    monofont: "Source Code Pro"
    monofontoptions: 
      - Scale=0.85
    
    # --- Layout and Styling---
    geometry:
      - "margin=0.75in"
    colorlinks: true
    linkcolor: "blue"
    urlcolor: "blue"
    link-citations: true
    
    # --- External Files ---
    include-in-header:
      - "latex-header.tex"
    keep-tex: false

# --- Document Language ---
lang: en
